### ISSUE TITLE
在node里面完全用不了，用require引入拿不到函数，用import也一样，都拿不到createPuzzle这个函数

### ISSUE THREAD

**Issue by HanBBQovo** [caijf/create-puzzle#1]
看图片
<img width="475" alt="Snipaste_2023-10-24_15-39-25" src="https://github.com/caijf/create-puzzle/assets/106244982/bc407e90-0e5e-438e-938a-d36359bda82a">
<img width="506" alt="Snipaste_2023-10-24_15-38-28" src="https://github.com/caijf/create-puzzle/assets/106244982/9b57fc8a-6cfc-47d5-92cf-4f62875a6bfd">

**Comment by caijf** [comment]
这个库使用浏览器 API 开发，所以仅支持浏览器端

**Comment by zhenzhenhan** [comment]
> 这个库使用浏览器 API 开发，所以仅支持浏览器端

以后有机会适配服务端吗？因为一般是服务端生成验证码图片，然后传给前端，前端去配合滑块验证码组件去生成。如果前端生成验证码图片，那后端就没办法拿到滑块的x坐标，这样只能在前端做验证，不安全。

**Comment by caijf** [comment]
@zhenzhenhan 最近折腾了一个 nodejs 版的拼图生成工具：https://github.com/caijf/node-puzzle
